### ISSUE TITLE
Allow parallel builds

### ISSUE THREAD

**Issue by wlevine** [rake-compiler/rake-compiler#114]
I think this would just require running `make -jN` instead of `make`. It doesn't look like there's a way to specify a custom make command.

**Comment by kou** [comment]
Could you try `MAKE="make -j8" rake ...`?

**Comment by wlevine** [comment]
Ah, that works, thanks for the tip.

**Comment by kou** [comment]
> Ah, that works, thanks for the tip.

No problem. :-)

**Comment by thedrow** [comment]
It should be documented somewhere.

**Comment by kou** [comment]
> It should be documented somewhere.

Could you send a pull request?
