### ISSUE TITLE
How do I use an existing non-Windows cross-Ruby?

### ISSUE THREAD

**Issue by ulfalizer** [rake-compiler/rake-compiler#119]
Hello,

Say I've already cross-compiled Ruby -- to another Linux system in this case. How do I tell rake-compiler to use that existing cross-compiled Ruby? I assume the compiler parameters (`CC`, etc.) will come from the cross-compiled Ruby's _rbconfig.rb_ file.

I'm guessing I'd have to manually add the compiler to _~/.rake-compiler/config.yml_ somehow, but I'm hazy on the exact format required.

What exactly does rake-compiler do with e.g. `RUBY_CC_VERSION=1.9.2` by the way? Does it simply search for "1.9.2" _anywhere_ in the left-hand side of the _config.yml_ mappings? If you don't specify `RUBY_CC_VERSION`, then what entry will it use? Perhaps some more documentation could be added here.

Thanks!

**Comment by larskanis** [comment]
Non Windows cross builds are supported by https://github.com/rake-compiler/rake-compiler-dock .
