### ISSUE TITLE
"make" fails with "file not recognized: File truncated"

### ISSUE THREAD

**Issue by rmosolgo** [rake-compiler/rake-compiler#122]
Hi, 

Thanks for this great tool! I'm trying out for the first time (first time with C, really), and I'm a bit stuck. 

On Travis, my [build](https://travis-ci.org/rmosolgo/graphql-libgraphqlparser-ruby/builds/107893604) succeeds with Ruby 2.2, but fails with Ruby 2.1. 

The default rake task is [`[:clobber, :compile, :test]`](https://github.com/rmosolgo/graphql-libgraphqlparser-ruby/blob/master/Rakefile#L17) and the error is: 

```
# .... 
make
compiling ../../../../ext/libgraphqlparser/visitor_functions.c
compiling ../../../../ext/libgraphqlparser/libgraphqlparser.c
linking shared-object libgraphqlparser.so
./libgraphqlparser.so: file not recognized: File truncated
collect2: ld returned 1 exit status
make: *** [libgraphqlparser.so] Error 1
rake aborted!
Command failed with status (2): [make...]
/home/travis/build/rmosolgo/graphql-libgraphqlparser-ruby/vendor/bundle/ruby/2.1.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:155:in `block (2 levels) in define_compile_tasks'
/home/travis/build/rmosolgo/graphql-libgraphqlparser-ruby/vendor/bundle/ruby/2.1.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:154:in `block in define_compile_tasks'
Tasks: TOP => default => compile => compile:x86_64-linux => compile:libgraphqlparser:x86_64-linux => copy:libgraphqlparser:x86_64-linux:2.1.5 => tmp/x86_64-linux/libgraphqlparser/2.1.5/libgraphqlparser.so
(See full trace by running task with --trace)
```

That error is coming from ExtensionTask calling `make` ([src](https://github.com/rake-compiler/rake-compiler/blob/v0.9.5/lib/rake/extensiontask.rb#L155)) -- so could it be an error in the generated Makefile?

A few things I tried: 

- Pointing the gemfile at `github: "rake-compiler/rake-compiler"`, in case the gem had some fix for this case. But of course that failed because the repo doesn't have a gemspec! 
- Adding `clobber` to the default Rake task because I read that `file not recognized: File truncated` could be caused by errors in previous compilations 
- Trying 2.1.5 locally (it succeeded)

Can you think of anything I should try here? Could it be a `g++` vs `clang` issue (I'm on a Mac, but Travis is ubuntu)? Or, am I barking up the wrong tree? (Feel free to close this issue if I'm asking in the wrong place!) 

Thanks!

**Comment by kou** [comment]
Does this problem occur without rake-compiler?

**Comment by rmosolgo** [comment]
Hmmm, I guess I could figure that out by replacing `rake compile` with a "custom" compile task, one that does each step by hand. 

I guess it's just

```
ruby extconf.rb
make 
``` 

?

**Comment by kou** [comment]
Yes.

**Comment by rmosolgo** [comment]
Ok, it turned out that the problem was in my project. 

My extension's filename `libgraphqlparser.c` was the same as my dependency's name `libgraphqlparser`. When I changed the extension's filename to `libgraphqlparser_ext.c`, I never saw this problem again! 

Thanks for your help, sorry to bother you!

**Comment by kou** [comment]
No problem. :-)

**Comment by Yashu1944** [comment]
I'm getting an error ( file not recognized: File truncated ) in vs code,
and also (collect2.exe: error: ld returned 1 exit status) but I have already saved my code.
this was too ( if ($?) { gcc first.c -o first } ; if ($?) { .\first )

**Comment by flavorjones** [comment]
@Yashu1944 Please open a new issue if you need assistance! Thank you!
