### ISSUE TITLE
rake-compiler 0.9.6 cannot find make

### ISSUE THREAD

**Issue by sodabrew** [rake-compiler/rake-compiler#123]
I am having trouble building on Windows with rake-compiler 0.9.6, whereas 0.9.5 works fine. Here are two AppVeyor builds showing the different behavior:

Works: https://ci.appveyor.com/project/sodabrew/mysql2/build/426
Fails: https://ci.appveyor.com/project/sodabrew/mysql2/build/425

I haven't dug into the problem yet, will dig in and update the ticket as I go. But if anything rings a bell for you guys, please let me know!

```
creating Makefile
cd - 
cd tmp/x64-mingw32/mysql2/2.2.4
rake aborted!
Couldn't find a suitable `make` tool. Use `MAKE` env to set an alternative.
C:/projects/mysql2/vendor/bundle/ruby/2.2.0/gems/rake-compiler-0.9.6/lib/rake/extensiontask.rb:451:in `make'
C:/projects/mysql2/vendor/bundle/ruby/2.2.0/gems/rake-compiler-0.9.6/lib/rake/extensiontask.rb:152:in `block (2 levels) in define_compile_tasks'
C:/projects/mysql2/vendor/bundle/ruby/2.2.0/gems/rake-compiler-0.9.6/lib/rake/extensiontask.rb:151:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x64-mingw32 => compile:mysql2:x64-mingw32 => copy:mysql2:x64-mingw32:2.2.4 => tmp/x64-mingw32/mysql2/2.2.4/mysql2.so
(See full trace by running task with --trace)
```

**Comment by kou** [comment]
Oh...
Thanks for your report. #109 related changes will be related.

**Comment by deivid-rodriguez** [comment]
Same problem here in `byebug`.

Fails: https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/457
Works: https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/458

Regards!

**Comment by kou** [comment]
Could you try 0.9.7?

**Comment by deivid-rodriguez** [comment]
Voila! It worked now! Thanks for the super quick fix!

**Comment by kou** [comment]
Thanks for confirming this!

**Comment by sodabrew** [comment]
Thanks so much!
