### ISSUE TITLE
Dependency on rspec < 3.4 causes failures in uses of rake-compiler

### ISSUE THREAD

**Issue by riddochc** [rake-compiler/rake-compiler#124]
A bug was recently fixed in rspec-core: https://github.com/rspec/rspec-core/commit/8e723fc805e901ac4fa5483837138b175d411d6e and rspec-core 3.4.4 has been released.  The Gemfile in rake-compiler doesn't restrict the version of rake; on my system, I have a variety of versions, including v11.0.1.  The Gemfile here does, however, restrict rspec to very old versions (2.x) which use obsoleted functions in rake, which in turn prevents rake-compiler from running.

Updating the Gemfile to use rspec "~> 3.4" causes a lot of specs to fail (because of obsoleted functions in rspec), but otherwise allows me to build and install rake-compiler 0.9.6 to use recent versions of rake.

One fix is to change the Gemfile with:
gem "rspec", "~> 3.4"
and fix the failing specs...

Another possible fix is to change the Gemfile to add
gem "rake", "~> ..."
to prevent too-new (?) versions of rake from being used with rake-compiler.

**Comment by kou** [comment]
Thanks for your report.

I want to migrate to test-unit from RSpec. test-unit doesn't have the problem for the Rake 11.0 change.

**Comment by larskanis** [comment]
This issue has been solved. It works successfully with `rspec-3.10`.
