### ISSUE TITLE
C GSL lib function not found at runtime 

### ISSUE THREAD

**Issue by mathieueh** [rake-compiler/rake-compiler#126]
Hello,

I have the following structure for my ruby project using rake:

|-- ext
|   -- analytics_circles
|       |-- extconf.rb
|       |-- analytics_circles.c
|-- lib
|   |-- analytics_circles.so

with analytics_circles.c containing the following line:
`#include <gsl/gsl_roots.h>`
which provides the following function `gsl_root_fsolver_bisection`

While `rake compile` succeeds, when running my ruby project:
`require File.expand_path('../lib/analytics_circles', __FILE__)`
I get the following runtime error:
`distance_calculator.rb:3:in require': lib/analytics_circles.so: undefined symbol: gsl_root_fsolver_bisection - lib/analytics_circles.so (LoadError)
	from distance_calculator.rb:3`

How can I build the .so file in a way that includes this function, in a static way? I am on Linux, and will want the solution to work on Mac as well.

Thanks,
M

**Comment by kou** [comment]
Is your `lib/analytics_circles.so` liked against `libgst.so`?

**Comment by mathieueh** [comment]
Hello, am not sure, but I managed to get this fixed by adding
`libs = ['-lgsl', '-lgslcblas', '-lm']
libs.each { |lib| $LOCAL_LIBS << "#{lib} " }`
to extconf.rb.
