### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by mrkn** [rake-compiler/rake-compiler#132]
I want the feature introduced by my previous two pull-requests, #128 and #129.
Please release the version 0.9.8 if any blockers don't exist.

**Comment by mrkn** [comment]
Once I have tried to use github version by specifying in Gemfile, but I couldn't to use it because this repository doesn't have `rake-compiler.gemspec`.

**Comment by kou** [comment]
I've released 0.9.8!

**Comment by mrkn** [comment]
Thanks!!
