### ISSUE TITLE
JavaExtensionTask broken

### ISSUE THREAD

**Issue by kaikuchn** [rake-compiler/rake-compiler#163]
Hey folks,

I think there was a bug introduced to the JavaExtensionTask with this commit f808dd7a74893d6269c6cc72e049d7bb85b84b65. I notice this because JRuby builds failed for a [PR I opened with Concurrent Ruby](https://github.com/ruby-concurrency/concurrent-ruby/pull/838). The Travis build log complains `NameError: undefined local variable or method `java_encoding_arg' for #<Rake::JavaExtensionTask:0x1568159>`. (See [here](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/629036975))

The above commit renames some things in the extension, which is why I assume it was a simple oversight to also adapt the usage of the renamed method.

Best regards,
Kai

**Comment by kaikuchn** [comment]
/ping @kou since you are probably are in the best position to judge what's going on here.

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.

@larskanis Could you update rake-compiler-dock to use rake-compiler 1.1.0?

**Comment by larskanis** [comment]
@kou Yes, will do.

**Comment by kou** [comment]
@larskanis Thanks!

**Comment by pitr-ch** [comment]
Thanks for the quick fix!
