### ISSUE TITLE
cross-compile to OSX from linux

### ISSUE THREAD

**Issue by pwoolcoc** [rake-compiler/rake-compiler#173]
In the cross-compilation docs it looks like cross-compilation is mostly for building windows gems from OSX or Linux, but is there a way to build an OSX native gem from a Linux host?

**Comment by kou** [comment]
No.
Because cross-compiler toolchain (such as MinGW for Windows) for macOS isn't provided on Linux.

**Comment by pwoolcoc** [comment]
@kou thanks!
