### ISSUE TITLE
[question] why do we build bundle instead dylib on Macos

### ISSUE THREAD

**Issue by CAMOBAP** [rake-compiler/rake-compiler#183]
subj.

Is it possible to build dylib somehow?

I use `ffi` and it doesn't recognize `*.bundle` out-of-the-box, so I need to do a platform-specific check to pass the correct name.

It will be nice to have a possibility to configure it on `rake-compiler` side

**Comment by CAMOBAP** [comment]
I just finished reading https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-osx. Per it `bundle` looks more suitable format for this proposed (`bundle` cannot be linked with other libs/apps, just can be loaded at runtime).

Are the same points were considered for `rake-compiler` to choose between `bundle` vs. `dylib`?

P.S. Asked question about `bundle` support https://github.com/ffi/ffi/issues/42#issuecomment-750031554

**Comment by kou** [comment]
Because Ruby uses `.bundle`.

See also: `ls $(ruby -e 'print RbConfig::CONFIG["archdir"]')`

What do you want to build with rake-compiler? Not Ruby's extension library?

**Comment by CAMOBAP** [comment]
> Because Ruby uses .bundle.

Got it

> What do you want to build with rake-compiler? Not Ruby's extension library?

"The regular" shared library, to use it with https://github.com/ffi/ffi later
