### ISSUE TITLE
how to build using static libraries

### ISSUE THREAD

**Issue by mcr** [rake-compiler/rake-compiler#193]
I am working on changes to the ruby-openssl gem, to support things in openssl which is not yet upstream.
I naturally have an openssl installation in a custom directory, and I run with --with-openssl-dir= 
The complexity of trying to do runtime testing of the code has turned me towards building openssl with no-shared so that the ruby-openssl openssl.so will have openssl statically compiled.  I can do this with:

   $LOCAL_LIBS="/sandel/3rd/openssl-dtls-api/lib/libssl.a /sandel/3rd/openssl-dtls-api/lib/libcrypto.a -lpthread"

inserted into the extconf.rb.  This works at build time, but does not work during function discovery time.
The problem is that the conftest items do not use this, and just have "-lssl", and of course, the system -lssl is just wrong.
(And it can't really be uninstalled)

I am looking for some more clue about how to modify the list of libraries that have_func() uses.

**Comment by kou** [comment]
It seems that this is not related to rake-compiler.
Is this really related to rake-compiler?

**Comment by mcr** [comment]
I've read/debugged through more code.
I now understand that a lot of this is done inside mkmf.rb, the relationship to rake compiler is really not well document.

In the end, I found that moving $LOCAL_LIBS to the top extconf.rb fixes my problems.
It would be great if rake-compiler could point to some documentation for mkmf.rb.
The mkmf documentation is also not great, sadly.
