### ISSUE TITLE
Breaking change with output location with 1.1.2

### ISSUE THREAD

**Issue by ankane** [rake-compiler/rake-compiler#194]
Hi, it looks like the latest release introduces a breaking change with the output location.

```ruby
Rake::ExtensionTask.new("field_test") do |ext|
  ext.name = "ext"
  ext.lib_dir = "lib/field_test"
end
```

Previously, this created `lib/field_test/ext.bundle`, but now it creates `lib/field_test/field_test/ext.bundle`.

**Comment by kou** [comment]
Oh... This should be fixed and we should release a new version.

**Comment by kou** [comment]
Could you show a project that uses this configuration?

**Comment by ankane** [comment]
Hey @kou, thanks for the fast response! Here's [the project / setup instructions](https://github.com/ankane/field_test#contributing).

**Comment by kou** [comment]
Thanks.
I've fixed this and released a new version.

**Comment by ankane** [comment]
Works great, thank you @kou! And thanks for this awesome project!!
