### ISSUE TITLE
rake-compiler 1.2.4 broken on Ruby 2.5 and below

### ISSUE THREAD

**Issue by ivoanjo** [rake-compiler/rake-compiler#224]
Hello there :wave:!

I work at @datadog on the [ddtrace](https://github.com/datadog/dd-trace-rb) gem. We use the `rake-compiler` gem to build our native extension, and it's extremely useful, thanks for your work on it! :pray: 

Yesterday our CI started failing after it picked up `rake-compiler` 1.2.4 [on Ruby 2.5 and below](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11295/workflows/3398c712-2e24-4785-8ca9-77c5a5a4f8d1/jobs/422511):

```
mkdir -p tmp/x86_64-linux/stage/lib
rake aborted!
NoMethodError: undefined method `cleanpath' for #<String:0x000055c199dee558>
/usr/local/bundle/ruby/2.3.0/gems/rake-compiler-1.2.4/lib/rake/extensiontask.rb:166:in `block in define_compile_tasks'
/usr/local/bundle/ruby/2.3.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
```

We've [had to pin](https://github.com/DataDog/dd-trace-rb/pull/3021) an older version of `rake-compiler` to work around this.

The issue seems to be that `#relative_path_from` in those Rubies doesn't work with strings:

https://github.com/rake-compiler/rake-compiler/blob/77d9294a203a11b39ee2e3d295e91706049b91ea/lib/rake/extensiontask.rb#L166

...I believe the fix would be to change it to:

```
relative_lib_path = Pathname(lib_path).relative_path_from(Pathname(tmp_path))
```

I can submit a PR if that helps!

**Comment by kou** [comment]
Oh, could you open a PR for this?

**Comment by ivoanjo** [comment]
Sounds good, I should have a PR for this within the next days! (Travelling a bit right now!)

**Comment by flavorjones** [comment]
I submitted PR #226

**Comment by kou** [comment]
Could you try 1.2.5?

**Comment by ivoanjo** [comment]
Yeap, can confirm it works now, thanks for the speedy fix :)
