### ISSUE TITLE
Support clang compile_commands.json

### ISSUE THREAD

**Issue by 4e554c4c** [rake-compiler/rake-compiler#230]
In order for much C editor tooling to work correctly, a [`compile_commands.json`](https://clangd.llvm.org/design/compile-commands) file must be generated by the build system, so that the editor tooling knows how a file is to be compiled.

This standard is supported by all modern C build systems, including Meson and CMake.

If rake-compiler supported generating a `compile_commands.json` it would be much easier to develop C extensions to ruby.

**Comment by kou** [comment]
I think that it should be done by `mkmf.rb` not rake-compiler.
Could you open an issue on https://bugs.ruby-lang.org/ instead of here?
