### ISSUE TITLE
Cross Compile looks for Ruby headers in the wrong directory

### ISSUE THREAD

**Issue by ParadoxV5** [rake-compiler/rake-compiler#232]
```
mkmf.rb can't find header files for ruby at <absolute/path/to/config/`tmp_dir`>/<`cross_platform`>/<`name`>/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.
```

Edit: It could be that I used my existing RubyIntaller2 prebuild instead of letting `rake-compiler` rebuild the entire Ruby from source.

### Analysis

Cross Compile currently works by replacing `RbConfig::CONFIG` with a `fake.rb` script in the `$LOAD_PATH`. This `fake.rb` copy-pastes the the target platform’s `rbconfig.rb` **verbatim**.
https://github.com/rake-compiler/rake-compiler/blob/9baeced144c20c3f40be2d678ac5b7f3ef4654a4/lib/rake/extensiontask.rb#L415-L435
However, `rbconfig.rb` begins with this for RubyIntaller2:
```ruby
# Ruby installed directory.
TOPDIR = File.dirname(__FILE__).chomp!("/lib/ruby/3.3.0/x64-mingw-ucrt")
```
Same for Ubuntu, for that matter:
```ruby
# Ruby installed directory.
TOPDIR = File.dirname(__FILE__).chomp!("/lib/ruby/3.3.0/x86_64-linux")
```

With `__FILE__` being `/path/to/project/tmp/fake.rb` rather than `/path/to/target/ruby/rbconfig.rb`, `RbConfig::TOPDIR` becomes `nil` and leads to a cascade of fallbacks.

**Comment by kou** [comment]
Do you want to cross compile on Windows?

**Comment by ParadoxV5** [comment]
I want(ed) to cross compile from WSL Ubuntu to Windows.

**Comment by kou** [comment]
Could you show all command lines you used for it? (How to reproduce this?)

**Comment by ParadoxV5** [comment]
1. Download and extract https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.0-1/rubyinstaller-3.3.0-1-x64.7z
2. `~/.rake-compiler/config.yml`:
   ```
   ---
   rbconfig-x64-mingw-3.3.0: /path/to/ruby33/ruby/lib/ruby/3.3.0/x64-mingw-ucrt/rbconfig.rb
   ```
3. Skip `rake-compile`, go straight to `rake cross compile`

**Comment by kou** [comment]
Thanks.
The usage isn't supported.
