### ISSUE TITLE
Bundler and RUBYOPT interfere with cross-compilation

### ISSUE THREAD

**Issue by luislavena** [rake-compiler/rake-compiler#96]
As identified in tjschuck/rake-compiler-dev-box#17, Bundler setting `RUBYOPT` interferes with the cross-compilation process.

It will be recommended unset `RUBYOPT` prior invoking the child process and later ensuring is restored.

**Comment by larskanis** [comment]
I think this is solved by https://github.com/rake-compiler/rake-compiler-dock by using a sandbox environment, that doesn't leak `RUBYOPT`.
